### ISSUE TITLE
[Issue] Hung & Crash, may be server connection?

### ISSUE THREAD

**Issue by trana315** [Spegeli/Pokemon-Go-Rocket-API#14]
`[05:57:44] [#1 of 25] retry request https://pgorelease.nianticlabs.com/plfe/326/rpc - Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\AT\Downloads\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30`

**Comment by trana315** [comment]
`[05:57:44] [#1 of 25] retry request https://pgorelease.nianticlabs.com/plfe/326/rpc - Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\AT\Downloads\Pokemon-Go-Rocket-API-master\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30`

**Comment by Spegeli** [comment]
Its mostly a bad server return.
Does it still exists?
